import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr-FR">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
					<div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-6">
						<div className="flex items-center gap-2">
							<a href="/" className="flex items-center gap-2">
								<div className="relative h-24 w-24 overflow-hidden">
									<Image
										src="/images/logo-edbm-light.png"
										alt="EDBM Logo"
										className="h-full w-full object-contain dark:hidden"
										width={96}
										height={96}
									/>
									<Image
										src="/images/logo-edbm-dark.png"
										alt="EDBM Logo"
										className="hidden h-full w-full object-contain dark:block"
										width={96}
										height={96}
									/>
								</div>
							</a>
						</div>
						<nav className="hidden md:flex items-center gap-6">
							<a
								href="/investir"
								className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
							>
								Pourquoi Madagascar
							</a>
							<a
								href="/secteurs"
								className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
							>
								Secteurs porteurs
							</a>
							<a
								href="/creation"
								className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
							>
								Création de société
							</a>
							<a
								href="/guides"
								className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
							>
								Guides pratiques
							</a>
							<a
								href="/contact"
								className="text-sm font-medium text-foreground/80 transition-colors hover:text-primary"
							>
								Contact
							</a>
						</nav>
						<div className="flex items-center gap-4">
							<div className="hidden md:flex items-center gap-2">
								<a
									href="/fr"
									className="text-xs font-medium text-foreground/70 transition-colors hover:text-primary"
								>
									FR
								</a>
								<span className="text-xs text-foreground/40">
									|
								</span>
								<a
									href="/en"
									className="text-xs font-medium text-foreground/70 transition-colors hover:text-primary"
								>
									EN
								</a>
							</div>
							<button
								className="inline-flex items-center justify-center rounded-md p-2 text-foreground/80 transition-colors hover:bg-accent hover:text-accent-foreground md:hidden"
								aria-label="Open menu"
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="24"
									height="24"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2"
									strokeLinecap="round"
									strokeLinejoin="round"
									className="h-6 w-6"
								>
									<line x1="4" x2="20" y1="12" y2="12"></line>
									<line x1="4" x2="20" y1="6" y2="6"></line>
									<line x1="4" x2="20" y1="18" y2="18"></line>
								</svg>
							</button>
						</div>
					</div>
				</header>
				<main>{children}</main>
				<footer className="border-t border-border/40 bg-muted/40 py-6">
					<div className="container mx-auto px-4 md:px-6">
						<div className="flex flex-col items-center justify-center text-center">
							<p className="text-xs text-muted-foreground">
								© {new Date().getFullYear()} Economic
								Development Board of Madagascar. Tous droits
								réservés.
							</p>
						</div>
					</div>
				</footer>
			</body>
		</html>
	);
}
